# Generated by Django 5.0.3 on 2024-04-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_full_name_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atmosphereRating', models.CharField(blank=True, max_length=100)),
                ('comfortAndMotivation', models.CharField(blank=True, max_length=100)),
                ('supportFromPeersAndSuperiors', models.CharField(blank=True, max_length=100)),
                ('communication', models.CharField(blank=True, max_length=100)),
                ('feelingValued', models.CharField(blank=True, max_length=100)),
                ('constructiveFeedback', models.CharField(blank=True, max_length=100)),
                ('growthOpportunities', models.CharField(blank=True, max_length=100)),
                ('trainingAndDevelopment', models.CharField(blank=True, max_length=100)),
                ('careerAdvancement', models.CharField(blank=True, max_length=100)),
                ('workLifeBalance', models.CharField(blank=True, max_length=100)),
                ('stressManagementSupport', models.CharField(blank=True, max_length=100)),
                ('flexibilityInSchedule', models.BooleanField(default=False)),
                ('overallSatisfaction', models.CharField(blank=True, max_length=100)),
                ('aspectsToImprove', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
