# Generated by Django 5.0.3 on 2024-04-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_kaizen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaizen',
            name='target_date',
        ),
    ]
